pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    bat 'go test -v ./... 2>&1 | go-junit-report > test-results.xml'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }

        stage('Unit Tests - FrontEnd') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true                        
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    bat '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        } 

        stage('launch Application') {
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true  
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'                                            
                }
            }
            steps {
                bat 'docker compose up --build -d'
            }
        }

        stage('API Tests') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.44.0-focal'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                dir('tests-api') {
                    bat 'npx wait-port http://localhost:8080/api/health -t 30000'
                    bat 'npm ci'
                    bat 'npx playwright test'
                }
            }
        }
    } // <--- Added missing closing brace for `stages`

    post {
        always {
            cleanWs()
        }
    }
}