pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'golang:1.20'
                    reuseNode true
                        
                    }
                }
            steps {
                dir('bugtracker-backend') {
                    bat 'go test -v ./...'
                }
                
            }
        }
    }
}
