pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image('golang:1.20').inside('-v /var/run/docker.sock:/var/run/docker.sock')
                    reuseNode true
                        
                    }
                }
            steps {
                dir('bugtracker-backend') {
                    bat 'go test -v ./...'
                }
                
            }
        }
    }
}
